name: Antonio Release Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to trigger a build manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/antonio-release.jks

      - name: Build Release APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PATH: "antonio-release.jks"

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Antonio-Release-v1
          path: app/build/outputs/apk/release/app-release.apk
