name: Chrome Ghost Cloud Build
on: 
  push:
    branches: [ main, master ]
  workflow_dispatch: # This adds a manual "Run" button in GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle' # This makes future builds much faster

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Compile Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Chrome-Ghost-Install-File
          path: app/build/outputs/apk/debug/*.apk
          